### ISSUE TITLE
local JSON file parsing stops processing

### ISSUE THREAD

**Issue by Emvee321** [philsmd/mongodb2hashcat#1] opened 2020-10-04 15:47 UTC
Just tested with a local JSON. It stops processing after the 6th entry. The 7th entry has a SHA256 only .
using: `mongo admin --eval 'var dumpFile = "users.json"' mongodb2hashcat.js`
See the embedded JSON input below.
The `mongo admin mongodb2hashcat.js` directly accessing the database with the same dataset, works as expected.

For creating the test userbase /json i used the different auth samples mentioned at
[mongo1](https://docs.mongodb.com/manual/reference/method/db.createUser/)
[mongo2](https://docs.mongodb.com/manual/tutorial/create-users/)
This userbase is a mix of entries using SHA256 only, certifcate or kerberos auth.

```
{ "_id" : "admin.hashcat", "userId" : UUID("3cf97f82-7ab9-4e09-ab24-d240ab590d94"), "user" : "hashcat", "db" : "admin", "credentials" : { "SCRAM-SHA-1" : { "iterationCount" : 10000, "salt" : "DgI+OYNZA1XAShcdUQXCZg==", "storedKey" : "FEQQOPtM6BZps4UVSxKRNk2e4LE=", "serverKey" : "IFn4aZh5LztmyDZb96O//I6v3V0=" }, "SCRAM-SHA-256" : { "iterationCount" : 15000, "salt" : "Wfq3vMoqSEAwCyLsQF/hk5C5cB0aLtWS9FHeuw==", "storedKey" : "OUYBeh+/fypyyQaXfFg1Yvi8+qSXl+I1CHioOrdgtJw=", "serverKey" : "KSsV1BssuAHZMF4l6ziZ/5LGjA/qsCBcf++HroqpGNY=" } }, "roles" : [ { "role" : "readWrite", "db" : "admin" }, { "role" : "dbAdmin", "db" : "admin" } ] }
{ "_id" : "products.accountAdmin01", "userId" : UUID("6a01c184-79fe-4b81-af97-2f520e69ffa7"), "user" : "accountAdmin01", "db" : "products", "credentials" : { "SCRAM-SHA-1" : { "iterationCount" : 10000, "salt" : "woXjHpF6z0NcU5bKkExCJQ==", "storedKey" : "d4+QalII2OdXT7+krPeyAWXpeOQ=", "serverKey" : "LcTdlvb1vScnQRp2H7PjN0bJ82U=" }, "SCRAM-SHA-256" : { "iterationCount" : 15000, "salt" : "YqmHwgomC7eT0JJF6dIj9o+3o7MiURzACXHPiw==", "storedKey" : "66DTGU8IwJKNk/FyAsBqUv8ZpIDZuLui1PWiSwTVUBg=", "serverKey" : "tGo+AvPCfMCemAZNg6K6TXTDSuGUTG2cWe0PbZ84fiQ=" } }, "customData" : { "employeeId" : 12345 }, "roles" : [ { "role" : "clusterAdmin", "db" : "admin" }, { "role" : "readAnyDatabase", "db" : "admin" }, { "role" : "readWrite", "db" : "products" } ] }
{ "_id" : "products.accountUser", "userId" : UUID("b0361465-ee95-47b9-b1a2-3350e372b252"), "user" : "accountUser", "db" : "products", "credentials" : { "SCRAM-SHA-1" : { "iterationCount" : 10000, "salt" : "UGUJtp9Q42CxCoeKon61PA==", "storedKey" : "sl6AyaxBSLfvM4sdIZYuKOaFZkM=", "serverKey" : "KFdmRfTfnt7P3doNdKiIOMeqwGk=" }, "SCRAM-SHA-256" : { "iterationCount" : 15000, "salt" : "Wa6q9DxU5UNBkY+SZ4+lhpRsIFgToW1hKMJOLg==", "storedKey" : "U+RlT1rEG1Ww/2tpTuf7LebVbyDJqBdYtzTnOgU9/+8=", "serverKey" : "jfblhIw2DOJaB1gfI93eFj0L7p7RxXzKoxczUloNyIo=" } }, "roles" : [ { "role" : "readWrite", "db" : "products" }, { "role" : "dbAdmin", "db" : "products" } ] }
{ "_id" : "admin.reportsUser", "userId" : UUID("82ef34bb-6456-4248-b48a-8ab6a299a94b"), "user" : "reportsUser", "db" : "admin", "credentials" : { "SCRAM-SHA-1" : { "iterationCount" : 10000, "salt" : "Gpt6meNIWD0/G/dSzqkepg==", "storedKey" : "Ev37U/pfnVOjNIQETccgqbmPH9E=", "serverKey" : "kzx5LWp2RXkJV+/39lGklfPndh4=" }, "SCRAM-SHA-256" : { "iterationCount" : 15000, "salt" : "BI6Lf4Hu5qtuSMvQbOLD+9wLvrvLRPIXwsm55g==", "storedKey" : "HuOJVMYjqQNjPByOR2Fqdwf9IXt9S+ttlFMpjBnO0n4=", "serverKey" : "uVmF95KT3Jyely/MAsNxpAIe0ZuOiI69bU1Mi988sX8=" } }, "roles" : [ ] }
{ "_id" : "admin.appAdmin", "userId" : UUID("9cde3641-08a6-4e22-83cb-275c699dcdbc"), "user" : "appAdmin", "db" : "admin", "credentials" : { "SCRAM-SHA-1" : { "iterationCount" : 10000, "salt" : "5ikEDWeYw/01QYYy+qmqTg==", "storedKey" : "xK/yEKKhRDW2nVcG+gTfOdljbIM=", "serverKey" : "pyeZO+pv0bVdE83z/ihebEUdfqY=" }, "SCRAM-SHA-256" : { "iterationCount" : 15000, "salt" : "uGYzl4nmvJZm9usLOmYSYzXble7pV2Rrd8LF1w==", "storedKey" : "9xzFFPFCyCrrNw25wtGZqhld1KnkmNpJEJ8DKzoSY+A=", "serverKey" : "O4gW1jpCecktz4Jn8U2lYLDsiVgazV/IgIA5PxHwMyE=" } }, "roles" : [ { "role" : "readWrite", "db" : "config" }, { "role" : "clusterAdmin", "db" : "admin" } ] }
{ "_id" : "admin.restricted", "userId" : UUID("08784fab-51a7-4bdb-88ad-4ddaa8f25e57"), "user" : "restricted", "db" : "admin", "credentials" : { "SCRAM-SHA-1" : { "iterationCount" : 10000, "salt" : "CE2plCkdb0W6LuHaqRlsjA==", "storedKey" : "QAea0pykv49GqYI6RBVlXdoHvSY=", "serverKey" : "2AXHKj3MH6Nkc3rydAtEWNYCwc8=" }, "SCRAM-SHA-256" : { "iterationCount" : 15000, "salt" : "O23jEGA7YGqHJGbfxlZuxhLA/CCRk8a3/wdfDA==", "storedKey" : "Gs606dZVQ6e021PMz6OXVGDQmMRnA0rdEZp3NbJoLxQ=", "serverKey" : "XnOptZrgYNbWLGPEe0v2YX+ke62MxGf07ATQ5riRid4=" } }, "authenticationRestrictions" : [ { "clientSource" : [ "192.0.2.0" ], "serverAddress" : [ "198.51.100.0" ] } ], "roles" : [ { "role" : "readWrite", "db" : "reporting" } ] }
{ "_id" : "reporting.reportUser256", "userId" : UUID("93d81e01-5d16-4ebf-b104-599d6934c8ab"), "user" : "reportUser256", "db" : "reporting", "credentials" : { "SCRAM-SHA-256" : { "iterationCount" : 15000, "salt" : "JsA8D7gFC9Nr4wWnwWWAfOCDcKgnjBKDGTQ/jQ==", "storedKey" : "AI4vQj3asRBHBddTiWghFo+FlcqIWTiKouF3VDHCuIY=", "serverKey" : "wTlPdZWzpCIoWzmIUJ3EGJD76RU4AnEG6Ovublo+pNw=" } }, "roles" : [ { "role" : "readWrite", "db" : "reporting" } ] }
{ "_id" : "reporting.reportsUser1", "userId" : UUID("a80cb545-8c22-4c29-8265-18a5fa1a2ccd"), "user" : "reportsUser1", "db" : "reporting", "credentials" : { "SCRAM-SHA-1" : { "iterationCount" : 10000, "salt" : "CUIPK76Vu2YcCoFv/btnaA==", "storedKey" : "eIc4fSM0G208g37N3Qj+bmfEcG4=", "serverKey" : "k1e7vzyU6AKuOvZqnzBgSKOBzyM=" }, "SCRAM-SHA-256" : { "iterationCount" : 15000, "salt" : "t0Fkl34s6CscgOPLdAqyp7t37kiTvR0tc59ncA==", "storedKey" : "w4kbFsoPM53taR5cTRNM5xOrfnlKfShSF1vhR+oW77s=", "serverKey" : "F9wuoRsCkzyzZSiWCuCSkK6pgU8p6A4dGhIsxGKm+ng=" } }, "roles" : [ { "role" : "read", "db" : "reporting" }, { "role" : "read", "db" : "products" }, { "role" : "read", "db" : "sales" }, { "role" : "readWrite", "db" : "accounts" } ] }
{ "_id" : "$external.reportingapp@EXAMPLE.NET", "userId" : UUID("9f5ef9c7-d8db-4746-b172-26cf32705c24"), "user" : "reportingapp@EXAMPLE.NET", "db" : "$external", "credentials" : { "external" : true }, "roles" : [ { "role" : "read", "db" : "records" } ] }
{ "_id" : "$external.reporting", "userId" : UUID("cca3b2f0-8fe9-49d0-96da-e4648d20d85d"), "user" : "reporting", "db" : "$external", "credentials" : { "external" : true }, "roles" : [ { "role" : "read", "db" : "records" } ] }
{ "_id" : "$external.CN=myName,OU=myOrgUnit,O=myOrg,L=myLocality,ST=myState,C=myCountry", "userId" : UUID("78c087bc-c717-4743-89a0-f7ddeda2c13a"), "user" : "CN=myName,OU=myOrgUnit,O=myOrg,L=myLocality,ST=myState,C=myCountry", "db" : "$external", "credentials" : { "external" : true }, "roles" : [ { "role" : "read", "db" : "records" } ] }
```

**Comment by philsmd** [comment] 2020-10-06 08:42
Thanks for testing and this problem report.

I'm pretty sure this exact problem was fixed with my latest commit from today (https://github.com/philsmd/mongodb2hashcat/commit/c373474f0ad0cbf4787dc46dbc42613f19053585) which added some sanity checks too.

The problem probably was that I didn't update the counter immediately as I do now within this line: https://github.com/philsmd/mongodb2hashcat/blob/c373474f0ad0cbf4787dc46dbc42613f19053585/mongodb2hashcat.js#L188
So the problem probably was that count wasn't increased in case of an error or missing (object) property or array entry and therefore the same index was tested again and again (as in an infitite loop).

Thanks again and do not hesitate to reopen if the problem isn't fixed with the latest version

**Closed by philsmd** 2020-10-06 08:42 UTC
